version: '3.7'
services:
  backend:
    image: water0641/tikitaka-api:0.1.0
    container_name: api
    hostname: api
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - SWAGGER_USER=${SWAGGER_USER}
      - SWAGGER_PASSWORD=${SWAGGER_PASSWORD}
    ports:
      - '8082:8082'
