version: '3.7'
services:
  # backend:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./
  #   container_name: api
  #   volumes:
  #     - ./:/app
  #   hostname: api
  #   environment:
  #     - MONGO_URI=${MONGO_URI}
  #     - PORT=${PORT}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - SWAGGER_USER=${SWAGGER_USER}
  #     - SWAGGER_PASSWORD=${SWAGGER_PASSWORD}
  #     - REDIS_HOST=${REDIS_HOST}
  #     - REDIS_PORT=${REDIS_PORT}
  #   ports:
  #     - '8082:8082'
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
